### ISSUE TITLE
编译的Nginx部署SM2双证书，通过客户端获取不到SM2证书链

### ISSUE THREAD

**Issue by aoguangjun1991** [Tongsuo-Project/Tongsuo#1]
老师，您好，我将babassl和Nginx一起编译，完成后部署上SM2双证书(签名证书含证书链+加密证书)。然后通过babassl编译生成的客户端程序，能获取到SM2证书信息，但是获取不到证书链信息。请问这个怎么解决呀？

**Comment by InfoHunter** [comment]
我怀疑是实际握手的时候使用了加密证书，你不需要部署加密证书

**Comment by InfoHunter** [comment]
可以贴一下你nginx的配置文件

**Comment by william-zk** [comment]
目前我们开源的国密实现是tls1.3+gm的标准，见https://tools.ietf.org/html/draft-yang-tls-tls13-sm-suites-03
这个标准不存在GM0024的双证书要求，单证书即可，整体流程和普通的TLS_AES_256_GCM_SHA384是一样的，你获取不到证书链的原因是你的加密证书和签名证书不是一条证书链，在标准的国际证书链验证流程下，是验证不过的

**Comment by aoguangjun1991** [comment]
> 可以贴一下你nginx的配置文件

这个是Nginx的HTTPS的配置文件
 # HTTPS server
    #
    server {
        listen       443 ssl;
        server_name  192.168.101.59;

        ssl_certificate      server.pem;
        ssl_certificate_key  server.key;
	  
	  ssl_certificate      SS.cert.pem;
        ssl_certificate_key  SS.key.pem;
	  
	  ssl_certificate      SE.cert.pem;
        ssl_certificate_key  SE.key.pem;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

	  ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;

        #ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
            root   html;
            index  index.html index.htm;
        }
    }
SS.cert.pem中包含了证书链，SE.cert.pem中没有证书链

**Comment by william-zk** [comment]
> 这个是Nginx的HTTPS的配置文件

实际用法只需要
```
server {
    listen       443 ssl;
    server_name  192.168.101.59;

    ssl_certificate      server.pem;
    ssl_certificate_key  server.key;
  
  ssl_certificate      SS.cert.pem;
    ssl_certificate_key  SS.key.pem;
  
   #ssl_certificate      SE.cert.pem;  不需要加密证书了
    #ssl_certificate_key  SE.key.pem;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

  ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;

    #ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    location / {
        root   html;
        index  index.html index.htm;
    }
}
```
然后可以使用babassl编译出来的二进制测试:
./openssl s_client -connect 192.168.101.59:443 -tls1_3 -ciphersuites TLS_SM4_GCM_SM3

**Comment by InfoHunter** [comment]
BabaSSL不支持GM/T 0024定义的双证书国密TLS协议，只支持TLS1.3+国密单证书的方式，具体技术方案见：https://datatracker.ietf.org/doc/draft-yang-tls-tls13-sm-suites/

**Comment by aoguangjun1991** [comment]
> > 这个是Nginx的HTTPS的配置文件
> 
> 实际用法只需要
> 
> ```
> server {
>     listen       443 ssl;
>     server_name  192.168.101.59;
> 
>     ssl_certificate      server.pem;
>     ssl_certificate_key  server.key;
>   
>   ssl_certificate      SS.cert.pem;
>     ssl_certificate_key  SS.key.pem;
>   
>    #ssl_certificate      SE.cert.pem;  不需要加密证书了
>     #ssl_certificate_key  SE.key.pem;
> 
>     ssl_session_cache    shared:SSL:1m;
>     ssl_session_timeout  5m;
> 
>   ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
> 
>     #ssl_ciphers  HIGH:!aNULL:!MD5;
>     ssl_prefer_server_ciphers  on;
> 
>     location / {
>         root   html;
>         index  index.html index.htm;
>     }
> }
> ```
> 
> 然后可以使用babassl编译出来的二进制测试:
> ./openssl s_client -connect 192.168.101.59:443 -tls1_3 -ciphersuites TLS_SM4_GCM_SM3

我将那个加密证书配置去掉之后，现在能获取到证书链了。
[
         {
            "commonName" : "sm2test.itrus.cn",
            "dateFrom" : "2020-05-29 16:02:57",
            "dateTo" : "2021-05-29 16:02:57",
            "issuer" : "vTrus SM2 SSL CA",
            "keySize" : "SM2256",
            "sha1Fing" : "5c188d9d6e361fe4b484276ff6bb58cc3df2c799",
            "sha256Fing" : "7864573294cb2e1a2b4277c14a6218961e35290e0eb43dc6b0e569afc4308cad",
            "signAlgo" : "SM2-with-SM3"
         },
         {
            "commonName" : "vTrus SM2 SSL CA",
            "dateFrom" : "2020-04-16 16:40:09",
            "dateTo" : "2033-04-16 16:40:09",
            "issuer" : "天威诚信数字认证中心根CA",
            "keySize" : "ECC256",
            "sha1Fing" : "5b35c5f74b4bd96930471b5c6664fbf3baceff90",
            "sha256Fing" : "dc41e322565e8184a9fd002e8fa8144609f15f4284ea9cfda50af6155db6375c",
            "signAlgo" : "SM2-with-SM3"
         },
         {
            "commonName" : "天威诚信数字认证中心根CA",
            "dateFrom" : "2013-05-09 16:43:13",
            "dateTo" : "2033-05-04 16:43:13",
            "issuer" : "ROOTCA",
            "keySize" : "ECC256",
            "sha1Fing" : "2a2a85381a6f3cba778f757f5866385d29708f07",
            "sha256Fing" : "2a3cac9c7de4019c43546c73fb5b00b7fda1b92adc8d85ba43e6a34898eb00d6",
            "signAlgo" : "SM2-with-SM3"
         }
      ]
谢谢老师

**Comment by aoguangjun1991** [comment]
> 目前我们开源的国密实现是tls1.3+gm的标准，见https://tools.ietf.org/html/draft-yang-tls-tls13-sm-suites-03
> 这个标准不存在GM0024的双证书要求，单证书即可，整体流程和普通的TLS_AES_256_GCM_SHA384是一样的，你获取不到证书链的原因是你的加密证书和签名证书不是一条证书链，在标准的国际证书链验证流程下，是验证不过的

去掉加密证书，现在可以了，谢谢

**Comment by aoguangjun1991** [comment]
> BabaSSL不支持GM/T 0024定义的双证书国密TLS协议，只支持TLS1.3+国密单证书的方式，具体技术方案见：https://datatracker.ietf.org/doc/draft-yang-tls-tls13-sm-suites/

好的，谢谢老师

**Comment by InfoHunter** [comment]
Issue resolved, closing...
