### ISSUE TITLE
How to test SNI on TLCP?

### ISSUE THREAD

**Issue by johnshajiang** [Tongsuo-Project/Tongsuo#232]
请问如何使用BabaSSL的s_server和s_client去测试ServerNameIndication？
对于原始的OpenSSL，需要提供两个server端证书，第二个证书由option -cert2和-key2指定。
那么，BabaSSL是否为TLCP的SNI测试提供了类似的option？

**Comment by dongbeiouba** [comment]
> 请问如何使用BabaSSL的s_server和s_client去测试ServerNameIndication？ 对于原始的OpenSSL，需要提供两个server端证书，第二个证书由option -cert2和-key2指定。 那么，BabaSSL是否为TLCP的SNI测试提供了类似的option？

感谢反馈，当前没办法直接使用BabaSSL的s_server和s_client测试TLCP SNI功能；
OpenSSL s_server通过配置SNI、cert2、key2来测试SNI功能的。

短期内想要测试的话：
方案一：客户端使用BabaSSL的s_client，服务端使用tengine + BabaSSL，（tengine master分支已经支持TLCP功能），测试TLCP SNI功能；
方案二：客户端使用BabaSSL的s_client，服务端修改现在的BabaSSL的s_server代码，修改现有逻辑，例如不需要加载cert2/key2，然后修改SNI匹配逻辑等。

后续我来跟踪一下这个问题，让BabaSSL支持使用s_server和s_client测试TLCP SNI功能。

**Comment by johnshajiang** [comment]
目前看，主要是s_server不支持设定多个主机证书，但s_client可以指定server name。
