### ISSUE TITLE
Compile error on RockyLinux8.

### ISSUE THREAD

**Issue by shove70** [Tongsuo-Project/Tongsuo#239]
output:
......
ar: crypto/bf/bf_enc.o: Too many open files
make[1]: *** [Makefile:6049: libcrypto.a] Error 1
make[1]: Leaving directory '/home/Downloads/BabaSSL-8.3.1'
make: *** [Makefile:176: all] Error 2

\# gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

\# ulimit -n
524288

\# cat /proc/sys/fs/file-max
9223372036854775807

**Comment by InfoHunter** [comment]
请发一下build的命令，如config和make的参数等

**Comment by shove70** [comment]
./config --prefix=/usr/local/babassl/
make
