### ISSUE TITLE
`perl config` error under Windows

### ISSUE THREAD

**Issue by i11010520** [Tongsuo-Project/Tongsuo#344]
the latest master tongsuo source:
commit 97554fd80259f1f303c0313adb12e855e99df116

>perl -v
This is perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x64-multi-thread

>perl config
Can't exec /bin/sh at config line 1.

**Comment by paladin-dalao** [comment]
![image](https://user-images.githubusercontent.com/85441544/233897160-db8954eb-504d-495f-baca-e4b21e266890.png)
