### ISSUE TITLE
lack of EVP_sm4_gcm() and EVP_sm4_ccm() in main

### ISSUE THREAD

**Issue by jyao1** [Tongsuo-Project/Tongsuo#347]
The original BabaSsl exposed EVP_sm4_gcm() and EVP_sm4_ccm().

But the Tongsuo main branch does not include those two symbols.

Missing feature?

**Comment by InfoHunter** [comment]
Did you mean that you encountered an error when running this example?  https://www.yuque.com/tsdoc/ts/zx1bok#XIs8E

**Comment by dongbeiouba** [comment]
> The original BabaSsl exposed EVP_sm4_gcm() and EVP_sm4_ccm().
> 
> But the Tongsuo main branch does not include those two symbols.
> 
> Missing feature?

I will add EVP_sm4_gcm() and EVP_sm4_ccm() ASAP.
Thanks!
