### ISSUE TITLE
Tongsuo 8.3.2 cannot be configured with api compatibility level setting to 3.0 explicitly

### ISSUE THREAD

**Issue by SeanTse** [Tongsuo-Project/Tongsuo#398]
Hi team,
I tried to configure Tongsuo 8.3.2 with the following command, but got error message: 
```
~/Tongsuo-8.3.2 # ./config shared enable-ntls -g --prefix=/usr/local/tongsuo --api=3.0
Operating system: x86_64-whatever-linux2

Failure!  build file wasn't produced.
Please read INSTALL and associated NOTES files.  You may also have to look over
your available compiler tool chain or change your configuration.

***** Unsupported api compatibility level: 3.0
```
Is Tongsuo 8.3.2 truly compatible with OpenSSL 3.0 API ?

**Comment by dongbeiouba** [comment]
To be compatible with OpenSSL 3.0 API, you should use Tongsuo master branch, instead of 8.3.2. 

Next release version based on master branch is 8.4.0.

**Comment by SeanTse** [comment]
Sorry, I didn't know that. Thanks for your help~
