### ISSUE TITLE
iOS项目导入工程使用后报错

### ISSUE THREAD

**Issue by stevension** [Tongsuo-Project/Tongsuo#412]
最新的master，使用
./config ios64-cross no-shared no-dso no-hw no-engine enable-ntls --prefix=/opt/tongsuo-ios64
编译出来的库与include下的头文件，导入工程使用后报错，报错信息如下：

In file included from include/openssl/evp.h:26:
In file included from include/openssl/types.h:21:
include/openssl/safestack.h:205:1: error: unknown type name 'ossl_unused'
SKM_DEFINE_STACK_OF_INTERNAL(OPENSSL_STRING, char, char)
^
include/openssl/safestack.h:39:12: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline t2 *ossl_check_##t1##_type(t2 *ptr) \
           ^
include/openssl/safestack.h:205:46: error: expected ';' after top level declarator
SKM_DEFINE_STACK_OF_INTERNAL(OPENSSL_STRING, char, char)
                                             ^
include/openssl/safestack.h:205:1: error: unknown type name 'ossl_unused'
SKM_DEFINE_STACK_OF_INTERNAL(OPENSSL_STRING, char, char)
^
include/openssl/safestack.h:43:12: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline const OPENSSL_STACK *ossl_check_const_##t1##_sk_type(const STACK_OF(t1) *sk) \
           ^
include/openssl/safestack.h:205:1: error: expected ';' after top level declarator
include/openssl/safestack.h:43:36: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline const OPENSSL_STACK *ossl_check_const_##t1##_sk_type(const STACK_OF(t1) *sk) \
                                   ^
include/openssl/safestack.h:205:1: error: unknown type name 'ossl_unused'
include/openssl/safestack.h:47:12: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline OPENSSL_STACK *ossl_check_##t1##_sk_type(STACK_OF(t1) *sk) \
           ^
include/openssl/safestack.h:205:1: error: expected ';' after top level declarator
include/openssl/safestack.h:47:36: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline OPENSSL_STACK *ossl_check_##t1##_sk_type(STACK_OF(t1) *sk) \
                                   ^
include/openssl/safestack.h:205:1: error: unknown type name 'ossl_unused'
include/openssl/safestack.h:51:12: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline OPENSSL_sk_compfunc ossl_check_##t1##_compfunc_type(sk_##t1##_compfunc cmp) \
           ^
include/openssl/safestack.h:205:1: error: expected ';' after top level declarator
include/openssl/safestack.h:51:36: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline OPENSSL_sk_compfunc ossl_check_##t1##_compfunc_type(sk_##t1##_compfunc cmp) \
                                   ^
include/openssl/safestack.h:205:1: error: unknown type name 'ossl_unused'
include/openssl/safestack.h:55:12: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline OPENSSL_sk_copyfunc ossl_check_##t1##_copyfunc_type(sk_##t1##_copyfunc cpy) \
           ^
include/openssl/safestack.h:205:1: error: expected ';' after top level declarator
include/openssl/safestack.h:55:36: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline OPENSSL_sk_copyfunc ossl_check_##t1##_copyfunc_type(sk_##t1##_copyfunc cpy) \
                                   ^
include/openssl/safestack.h:205:1: error: unknown type name 'ossl_unused'
include/openssl/safestack.h:59:12: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline OPENSSL_sk_freefunc ossl_check_##t1##_freefunc_type(sk_##t1##_freefunc fr) \
           ^
include/openssl/safestack.h:205:1: error: expected ';' after top level declarator
include/openssl/safestack.h:59:36: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline OPENSSL_sk_freefunc ossl_check_##t1##_freefunc_type(sk_##t1##_freefunc fr) \
                                   ^
include/openssl/safestack.h:231:1: error: unknown type name 'ossl_unused'
SKM_DEFINE_STACK_OF_INTERNAL(OPENSSL_CSTRING, const char, char)
^
include/openssl/safestack.h:39:12: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline t2 *ossl_check_##t1##_type(t2 *ptr) \
           ^
include/openssl/safestack.h:231:47: error: expected ';' after top level declarator
SKM_DEFINE_STACK_OF_INTERNAL(OPENSSL_CSTRING, const char, char)
                                              ^
include/openssl/safestack.h:231:1: error: unknown type name 'ossl_unused'
SKM_DEFINE_STACK_OF_INTERNAL(OPENSSL_CSTRING, const char, char)
^
include/openssl/safestack.h:43:12: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline const OPENSSL_STACK *ossl_check_const_##t1##_sk_type(const STACK_OF(t1) *sk) \
           ^
include/openssl/safestack.h:231:1: error: expected ';' after top level declarator
include/openssl/safestack.h:43:36: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline const OPENSSL_STACK *ossl_check_const_##t1##_sk_type(const STACK_OF(t1) *sk) \
                                   ^
include/openssl/safestack.h:231:1: error: unknown type name 'ossl_unused'
include/openssl/safestack.h:47:12: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline OPENSSL_STACK *ossl_check_##t1##_sk_type(STACK_OF(t1) *sk) \
           ^
include/openssl/safestack.h:231:1: error: expected ';' after top level declarator
include/openssl/safestack.h:47:36: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline OPENSSL_STACK *ossl_check_##t1##_sk_type(STACK_OF(t1) *sk) \
                                   ^
include/openssl/safestack.h:231:1: error: unknown type name 'ossl_unused'
include/openssl/safestack.h:51:12: note: expanded from macro 'SKM_DEFINE_STACK_OF_INTERNAL'
    static ossl_unused ossl_inline OPENSSL_sk_compfunc ossl_check_##t1##_compfunc_type(sk_##t1##_compfunc cmp) \
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

<img width="1400" alt="image" src="https://github.com/Tongsuo-Project/Tongsuo/assets/10590215/f8ac9dd3-c913-4bbc-8c43-833ef7e861b9">
<img width="699" alt="image" src="https://github.com/Tongsuo-Project/Tongsuo/assets/10590215/c1f0d813-93bf-4591-b0ee-ef29c4c6c0d2">

环境为Xcode14.0.1

**Comment by stevension** [comment]
修改编译选项后解决

**Comment by 18611429192** [comment]
朋友，改什么了？
