### ISSUE TITLE
Tongsuo and NTLS support in Angie (nginx fork)

### ISSUE THREAD

**Issue by VBart** [Tongsuo-Project/Tongsuo#421]
Dear Tongsuo developers,

I'm happy to inform you, that full support for Tongsuo library and NTLS has been added into recent version of Angie 1.2.0.

Angie is an open source fork of nginx made by some of its former core developers. You can find more information on the project documentation website: https://angie.software/en/ and GitHub page: https://github.com/webserver-llc/angie

It would be nice, if you mention it in your project pages. Thanks!

**Comment by InfoHunter** [comment]
Good to know Tongsuo is integrated into Angie! We need to add an application list to show our users on both tongsuo.net and Github README page first, and then we will add Angie into the list.

BTW it's interesting to know some nginx core people made a new fork of nginx. Since some guys of Tongsuo development team (including me) also used to work on Alibaba's nginx fork (the Tengine) in the past decade, I am a little curious on the motivation of the creation of Angie (and what will be different from Angie and original nginx in the future?)

**Comment by InfoHunter** [comment]
Hmmm, I googled a bit and I found this article: https://blog.desdelinux.net/en/angie-la-bifurcacion-de-nginx-creada-por-desarrolladores-que-abandonaron-f5/

**Comment by VBart** [comment]
I had been working in Moscow, Russia in NGINX, Inc. (the company behind nginx development) for 10+ years, since almost the foundation in 2011. In 2019, the American based corporation F5 Networks acquired NGINX. In April of 2022, due to political reasons, F5 shut down all the operations in Russia (see: https://my.f5.com/manage/s/article/K59427339).

Being not able to continue our work, I, with a group of some other former employees, decided to create a new company and fork nginx. Our intention is to continue development under a new name and make it much better than the original version by adding new features, that for some reasons haven't been added before. We are going to maintain backward compatibility with nginx as long as possible, but cannot guarantee it in a long distance, since some changes just cannot be made without significant improvements to nginx core API.

**Comment by InfoHunter** [comment]
That sounds reasonable. Wish everything goes well with you guys and the new born Angie.

**Comment by VBart** [comment]
Thanks!

Btw, we're considering building Angie packages with Tongsuo. Do you know if there are any Linux distributions where Tongsuo library shipped in repositories? Otherwise, the only option seems to build Angie with Tongsuo together. Maybe you could suggest on what systems we should focus, what systems are the most popular among Tongsuo users?

**Comment by InfoHunter** [comment]
> Btw, we're considering building Angie packages with Tongsuo. Do you know if there are any Linux distributions where Tongsuo library shipped in repositories? Otherwise, the only option seems to build Angie with Tongsuo together. Maybe you could suggest on what systems we should focus, what systems are the most popular among Tongsuo users?

I think CentOS and its variants are still very popular in Tongsuo users. Unfortunately I don't know any distro that contains Tongsuo by default, so yes it seems Angie needs to build Tongsuo together in an RPM or so

**Comment by MarcoMarcoaldi** [comment]
> I had been working in Moscow, Russia in NGINX, Inc. (the company behind nginx development) for 10+ years, since almost the foundation in 2011. In 2019, the American based corporation F5 Networks acquired NGINX. In April of 2022, due to political reasons, F5 shut down all the operations in Russia (see: https://my.f5.com/manage/s/article/K59427339).
> 
> Being not able to continue our work, I, with a group of some other former employees, decided to create a new company and fork nginx. Our intention is to continue development under a new name and make it much better than the original version by adding new features, that for some reasons haven't been added before. We are going to maintain backward compatibility with nginx as long as possible, but cannot guarantee it in a long distance, since some changes just cannot be made without significant improvements to nginx core API.

Hi Vbart, i suggest you to contact Tao Bao Group, the Chinese company developed OpenResty forked from NGINX. I think China is Russia Friend and disposable to assume all ex nginx developer.

Best Regards

**Comment by VBart** [comment]
Thank you for the recommendations!

**Comment by InfoHunter** [comment]
Hi @VBart , as discussed earlier, I added Angie as one recommended web server project in both [README](https://github.com/Tongsuo-Project/Tongsuo/tree/master#readme) and https://www.tongsuo.net/eco/ . Currently both of them are written in Chinese mainly, so I guess you may need use something like google translate...

**Comment by InfoHunter** [comment]
OpenResty is not developed by Taobao, but Tengine is

**Comment by VBart** [comment]
> Hi @VBart , as discussed earlier, I added Angie as one recommended web server project in both [README](https://github.com/Tongsuo-Project/Tongsuo/tree/master#readme) and https://www.tongsuo.net/eco/ . Currently both of them are written in Chinese mainly, so I guess you may need use something like google translate...

Awesome! Thank you very much.

Tongsuo library is already mentioned in our [features list](https://angie.software/en/#functionality) on the main page as well as in [the related directives description](https://angie.software/en/http_ssl/#ssl-ntls).

We're happy to cooperate. 🍻

**Comment by VBart** [comment]
Just to let you know, we've launched a Chinese version of the Angie documentation: https://cn.angie.software/angie/docs/

**Comment by InfoHunter** [comment]
Cool, this is really nice!
