### ISSUE TITLE
请问有类似 OPENSSL_IS_TONGSUO 之类的宏吗？

### ISSUE THREAD

**Issue by timonwong** [Tongsuo-Project/Tongsuo#425]
我们最近在将 envoy 改成 openssl，不过需要一些额外的宏来进行条件编译（比如 RFC8998 SM 强制签名 和 NTLS 支持）

**Comment by InfoHunter** [comment]
没有，但是貌似可以用TONGSUO_VERSION_NUMBER来判断是否是Tongsuo

**Comment by timonwong** [comment]
谢谢，因为 TONGSUO_VERSION_NUMBER 看起来在 8.3 上没有，暂时使用的 `BABASSL_VERSION_NUMBER`

**Comment by libratiger** [comment]
@timonwong  我们最近也在调研 envoy和 guomi，后来你们走通了没有？不太确定https://github.com/Tongsuo-Project/envoy-tongsuo 这个项目维护情况如何

**Comment by timonwong** [comment]
> [@timonwong](https://github.com/timonwong) 我们最近也在调研 envoy和 guomi，后来你们走通了没有？不太确定https://github.com/Tongsuo-Project/envoy-tongsuo 这个项目维护情况如何

@libratiger 

走通了，改动比较大。RFC 8998 还比较简单，直接用即可。国密双证书是通过 certificates 里面一个个识别其 usage 来判断是签名证书还是加密证书的。

我们主要是 Istio 集成，最高也就到了 Istio 1.18，后续没有再维护。

另外我们主要是参考了 maistra (RedHat Openshift) 的工作，https://github.com/maistra/envoy
红帽因为 FIPS 的要求是切到了 OpenSSL，很有参考价值

**Comment by libratiger** [comment]
@timonwong 感谢你的回复。

我们只想直接用就行了。听起来 envoy-tongsuo 这个项目还是需要自己修改代码是吗？

> 国密双证书是通过 certificates 里面一个个识别其 usage 来判断是签名证书还是加密证书的。

这个方便说的更细吗？

我们就是简单的使用envoy，以及用到 mTLS。

**Comment by timonwong** [comment]
> [@timonwong](https://github.com/timonwong) 感谢你的回复。
> 
> 我们只想直接用就行了。听起来 envoy-tongsuo 这个项目还是需要自己修改代码是吗？
> 
> > 国密双证书是通过 certificates 里面一个个识别其 usage 来判断是签名证书还是加密证书的。
> 
> 这个方便说的更细吗？
> 
> 我们就是简单的使用envoy，以及用到 mTLS。

@libratiger envoy-tongsuo 很久都没更新了，我没试过。上游的 envoy-openssl 也用不了，至少不能无痛直接用。

NTLS 支持还需要额外的做一些侵入性改动。比如 tls_inspector 里面设置了 min,max #513，需要去掉

transport_sockets/tls 下面需要对双证书进行适配。得重新写一个 handshaker。遍历 tls_certificates，找到 sign 和 enc cert，然后调用铜锁 API

工作量不小，具体的技术细节不便透露了。不过我们的代码改动量大概在 ~2K 左右

**Comment by libratiger** [comment]
如果单纯的是网络通信的 TLS 支持国密加密，看起来是使用支持国密 nginx 比较靠谱了？ @timonwong

**Comment by timonwong** [comment]
> 如果单纯的是网络通信的 TLS 支持国密加密，看起来是使用支持国密 nginx 比较靠谱了？ [@timonwong](https://github.com/timonwong)

@libratiger 只是作为入口、代理的话，nginx 更合适。这块很成熟了
