### ISSUE TITLE
自定义前缀编译，部分前缀添加错误

### ISSUE THREAD

**Issue by yaoyue** [Tongsuo-Project/Tongsuo#437]
您好，我使用编译配置  --symbol-prefix 设置的前缀为 “senxxx_”  ，但是使用本地编译和 iOS 交叉编译，发现部分符号被替换成了  " _ senxxx_ " ，导致最终生成的静态库，导入项目编译报错，怎么问题，有办法解决嘛？

编译配置
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/10718825/a96ef67d-052f-4b5c-8566-cc2f4e64c77d)

生成的静态库
[libcrypto.a.zip](https://github.com/Tongsuo-Project/Tongsuo/files/11867883/libcrypto.a.zip)
[libssl.a.zip](https://github.com/Tongsuo-Project/Tongsuo/files/11867888/libssl.a.zip)

使用 .a  再生成 framework 后，导入 iOS 项目使用，编译报错
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/10718825/80365fe1-9f01-4f3c-a9db-656d94d26182)

**Comment by wa5i** [comment]
我看 libcrypto.a 里面已经加了前缀了。你执行命令看看 `nm -A libcrypto.a | grep ' T ' `，应该是你的编译器没有依赖新编译的 libcrypto.a 吧

**Comment by yaoyue** [comment]
如果没有依赖新编译的 libcrypto.a，应该不会报错 `Undefined symbol: _senxxx_EVP_sm3`，因为头文件里面找不到 `_senxxx_EVP_sm3 `  这个函数，所以  `_senxxx_EVP_sm3 ` 是 libcrypto.a 内部调用到的，而  “ _ senxxx_”  前缀，肯定是 tongsuo 编译自定义生成的。
也就是说，应该是部分方法调用的前缀，被加成了 _ senxxx_，但是方法定义增加的前缀是 senxxx_，所以导致有些函数或变量未定义，出现 `Undefined symbol` 报错

**Comment by wa5i** [comment]
有完整的报错信息和工程编译参数吗，发上来看看

**Comment by yaoyue** [comment]
已解决，感谢大佬们耐心指教 ~

**Comment by PXLZHM** [comment]
> 已解决，感谢大佬们耐心指教 ~

大佬，我也遇到这个问题了，这个是如何解决的
