### ISSUE TITLE
-Wl,-rpath,/opt/tongsuo/lib 直接编译后的产物未生成到此目录下

### ISSUE THREAD

**Issue by Heart-Beats** [Tongsuo-Project/Tongsuo#449]
大佬，我是从事安卓应用层开发，所以对 C 相关开发不是很了解，我按照文档配好相关编译环境后，根据[源码编译](https://www.yuque.com/tsdoc/ts/rp7ul8a4ttav8ql9 ) 进行相关配置，使用`../config -Wl,-rpath,/opt/tongsuo/lib no-asm enable-ntls android-arm64`编译完成没有报错：
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/33248551/ad26d549-4e23-4fc9-9305-ce06ffb481ff)
但是发现指定的目录下没有任何产物：
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/33248551/36a5cd8c-4ac8-408c-9619-8049608f7155)
相应的产物都在编译目录下面：
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/33248551/4f403548-b82d-4e80-a343-a7ea17229db1)

只有执行 `make install` 后才在 /opt/tongsuo/lib 这个目录下生成相应的文件，所以是必须要执行 `make install` 才能得到自己想要的文件吗？

**Comment by FullyRobert** [comment]
是的，make install 用于将编译好的程序或库文件安装到指定的目录中。

**Comment by Heart-Beats** [comment]
> 是的，make install 用于将编译好的程序或库文件安装到指定的目录中。

好的，我现在这边生成了编译产物：
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/33248551/5192fb9d-7a56-43c6-9a7f-a91bcddcaf38)
想在项目中使用相关的动态库，但目前遇到的一个问题是相应的头文件不知去哪去找，我看编译完成后有 include 目录：
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/33248551/88bb6c53-2b7c-4b3a-ab94-1ddc3f69d786)
源码下也有相应的头文件目录：
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/33248551/54fff900-e5b6-44fe-ab02-391c13c8af88)
同时在编译目录下也生成了相应的头文件目录：
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/33248551/ac48a571-9eed-46b6-b26e-f1b6c8974cd9)

那么我在使用相应的动态库时，如何找到正确的头文件呢？难道需要根据  Makefile 文件找到对应的规则，然后再从源码中确定引入的头文件吗？

**Comment by wa5i** [comment]
> > 是的，make install 用于将编译好的程序或库文件安装到指定的目录中。
> 
> 好的，我现在这边生成了编译产物： ![image](https://user-images.githubusercontent.com/33248551/254221291-5192fb9d-7a56-43c6-9a7f-a91bcddcaf38.png) 想在项目中使用相关的动态库，但目前遇到的一个问题是相应的头文件不知去哪去找，我看编译完成后有 include 目录： ![image](https://user-images.githubusercontent.com/33248551/254221963-88bb6c53-2b7c-4b3a-ab94-1ddc3f69d786.png) 源码下也有相应的头文件目录： ![image](https://user-images.githubusercontent.com/33248551/254222285-54fff900-e5b6-44fe-ab02-391c13c8af88.png) 同时在编译目录下也生成了相应的头文件目录： ![image](https://user-images.githubusercontent.com/33248551/254222639-ac48a571-9eed-46b6-b26e-f1b6c8974cd9.png)
> 
> 那么我在使用相应的动态库时，如何找到正确的头文件呢？难道需要根据 Makefile 文件找到对应的规则，然后再从源码中确定引入的头文件吗？

如果使用 gcc 或者clang 编译的话，可以用 -I 参数指定查询头文件的目录，使用-L 参数指定库的目录

**Comment by Heart-Beats** [comment]
目前已可正常引入相关头文件
