### ISSUE TITLE
铜锁支持的浏览器类型

### ISSUE THREAD

**Issue by successjian** [Tongsuo-Project/Tongsuo#457]
请问下， 8.3.2版本的铜锁支持mac和window系统下哪些国密浏览器以及浏览器版本？

**Comment by InfoHunter** [comment]
360是测试过的，其他的请 @dongbeiouba 补充

**Comment by successjian** [comment]
> 
@dongbeiouba 麻烦告知下8.3.2版本的铜锁支持mac和window系统下哪些国密浏览器以及浏览器版本？

**Comment by dongbeiouba** [comment]
测试以360企业浏览器为主，我在Mac下测试的，360企业浏览器同时支持MacOS和Windows的，具体版本没有记录，你使用最新版就行。

密信浏览器我记着也验证过，支持Windows系统，目前应该还不支持MacOS。

其他浏览器你也可以试试，比如红莲花浏览器，支持Windows系统，目前应该还不支持MacOS。

如果遇到国密浏览器和铜锁的通信有任何问题，欢迎提交issue或进群交流。

**Comment by successjian** [comment]
> 测试以360企业浏览器为主，我在Mac下测试的，360企业浏览器同时支持MacOS和Windows的，具体版本没有记录，你使用最新版就行。
> 
> 密信浏览器我记着也验证过，支持Windows系统，目前应该还不支持MacOS。
> 
> 其他浏览器你也可以试试，比如红莲花浏览器，支持Windows系统，目前应该还不支持MacOS。
> 
> 如果遇到国密浏览器和铜锁的通信有任何问题，欢迎提交issue或进群交流。

好的，谢谢。
