### ISSUE TITLE
tongsuo编译问题

### ISSUE THREAD

**Issue by successjian** [Tongsuo-Project/Tongsuo#458]
在mac下建立的虚拟机（arm机器）编译tongsuo，发生报错如下：

[root@gmssl Tongsuo-8.3.2]# ./config enable-ec_elgamal enable-paillier enable-ntls
Operating system: aarch64-whatever-linux2

Failure!  build file wasn't produced.
Please read INSTALL and associated NOTES files.  You may also have to look over
your available compiler tool chain or change your configuration.

***** Unsupported options: enable-paillier

查询了一些资料，未找到答案，麻烦解答下，谢谢！

**Comment by wa5i** [comment]
8.3.2 没有支持 paillier，请使用 8.4.0-pre1 或者 master分支的代码试一下

**Comment by successjian** [comment]
> 8.3.2 没有支持 paillier，请使用 8.4.0-pre1 或者 master分支的代码试一下

好的

**Comment by wa5i** [comment]
问题解决，这个 issue 我关闭了
