### ISSUE TITLE
s_server/s_client如何才能使用aes-128-cbc-hmac-sha256这种算法？

### ISSUE THREAD

**Issue by foxriver1025** [Tongsuo-Project/Tongsuo#466]
请教下，s_server和s_client怎样的命令配置可以使用aes-128-cbc-hmac-sha256算法？
我使用如下命令报错了：
openssl s_client -connect 127.0.0.1:4433 -cipher aes-128-cbc-hmac-sha256
Call to SSL_CONF_cmd(-cipher, aes-128-cbc-hmac-sha256) failed
809B4E26167F0000:error:0A0000B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl/ssl_lib.c:2837.

**Comment by wa5i** [comment]
```
openssl s_client -connect 127.0.0.1:4433 -cipher AES128-SHA256
```

**Comment by foxriver1025** [comment]
@wa5i 使用这条命令确实没报错，但是实际上未调用到provider实现的aes-128-cbc-hmac-sha256。
我使用tongsuo + qatprovider。
s_server:
/opt/tongsuo/bin/openssl s_server -provider qatprovider -cert server-rsa-sign.crt -key server-rsa-sign.key -accept 127.0.0.1:4433
s_client:
/opt/tongsuo/bin/openssl s_client  -connect 127.0.0.1:4433 -cipher AES128-SHA256 -tls1_2
协商成功了，显示
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES128-SHA256
但是在server端，没有调用到provider里注册的算法。
而使用speed命令是可以调用到provider里注册的算法的：
/opt/tongsuo/bin/openssl speed -provider qatprovider -evp aes-128-cbc-hmac-sha256
所以还是想再请教下s_server/s_client如何能调用到provider里注册的aes-128-cbc-hmac-sha256

**Comment by wa5i** [comment]
我自己 gdb 是可以调用到 defprov 里面的 AES128-CBC 函数 cipher_hw_aesni_cbc，在 ossl_cipher_generic_block_update 里面通过 ctx->hw->cipher 函数指针调用到，怀疑是你的 qatprovider 里面实现的问题，你可以 gdb 试试。

**Comment by foxriver1025** [comment]
@wa5i 好的，多谢，我大概知道原因了，openssl默认是先加密再计算mac的，我加了参数-no_etm后可以调用到provider里注册的算法了

**Comment by wa5i** [comment]
问题已解，我把这个 issue 关闭了
