### ISSUE TITLE
Bulletproofs Range 使用教程编译通过无法运行代码

### ISSUE THREAD

**Issue by whitesmoker3** [Tongsuo-Project/Tongsuo#467]
想问下在铜锁 Bulletproofs Range 使用教程，我编译通过，运行时却提示我说error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or directory

![CBZU6D_C)YJ(KY3 R%3_I39](https://github.com/Tongsuo-Project/Tongsuo/assets/141142754/9a6c737e-aac0-4818-9d00-243f4acc57fa)

**Comment by whitesmoker3** [comment]
已解决，参考SM类命令“gcc sm2_verify.c -I/opt/tongsuo/include -L/opt/tongsuo/lib64 -lcrypto -Wl,-rpath=/opt/tongsuo/lib64”，添加-Wl,-rpath=/opt/tongsuo/lib64指定编译出的 openssl 二进制程序依赖的 libcrypto.so 和 libssl.so 目录即可

**Comment by wa5i** [comment]
> 已解决，参考SM类命令“gcc sm2_verify.c -I/opt/tongsuo/include -L/opt/tongsuo/lib64 -lcrypto -Wl,-rpath=/opt/tongsuo/lib64”，添加-Wl,-rpath=/opt/tongsuo/lib64指定编译出的 openssl 二进制程序依赖的 libcrypto.so 和 libssl.so 目录即可

是的，这是找不到动态库的原因，加上-rpath 编译或者运行时设置环境变量LD_LIBRARY_PATH=/opt/tongsuo/lib64都可以
