### ISSUE TITLE
实现 RFC 8998 的浏览器有哪些？

### ISSUE THREAD

**Issue by timonwong** [Tongsuo-Project/Tongsuo#470]
目前是不是只有 360 安全浏览器的「国产」版提供了 RFC 8998 支持？还是有其他的？

**Comment by zzl360** [comment]
欢迎使用360安全浏览器信创版访问[https://rfc8998.badgmssl.com/](https://rfc8998.badgmssl.com/) 和 [https://rfc8998only.badgmssl.com/ ](https://rfc8998only.badgmssl.com/ )来验证rfc8998。

**Comment by zzl360** [comment]
实际上，360安全浏览器的企业版（windows/linux/mac）也支持rfc8998

**Comment by timonwong** [comment]
> 实际上，360安全浏览器的企业版（windows/linux/mac）也支持rfc8998

谢谢，信创版是确定支持的，但是我用（单机版/网络版，在这里下载 https://browser.360.net/）的企业浏览器测试 https://rfc8998only.badgmssl.com/ 都无法访问。
访问 https://rfc8998.badgmssl.com/ 看证书仍然是 RSA 的，不是 RFC 8998

@zzl360 是需要特殊的版本吗？

**Comment by zzl360** [comment]
> > 实际上，360安全浏览器的企业版（windows/linux/mac）也支持rfc8998
> 
> 谢谢，信创版是确定支持的，但是我用（单机版/网络版，在这里下载 [https://browser.360.net/）的企业浏览器测试](https://browser.360.net/%EF%BC%89%E7%9A%84%E4%BC%81%E4%B8%9A%E6%B5%8F%E8%A7%88%E5%99%A8%E6%B5%8B%E8%AF%95) https://rfc8998only.badgmssl.com/ 都无法访问。 访问 https://rfc8998.badgmssl.com/ 看证书仍然是 RSA 的，不是 RFC 8998
> 
> @zzl360 是需要特殊的版本吗？

是的，我们内部在研的企业版支持，很快就可以发布了

**Comment by foxriver1025** [comment]
@zzl360 请教下，360信创版在哪里下载

**Comment by zzl360** [comment]
https://browser.360.net/gc/index.html @foxriver1025

**Comment by ShuiHuo** [comment]
有免费开源支持 Linux 系统的吗？
