### ISSUE TITLE
运行EC_Elgamal_test报错relocation error:

### ISSUE THREAD

**Issue by lit18329436479** [Tongsuo-Project/Tongsuo#472]
按照铜锁手册运行ec_elgamal用例参考：https://www.yuque.com/tsdoc/ts/permw6
编译成功,运行报错：./ec_elgamal_test: relocation error: ./ec_elgamal_test: symbol EC_ELGAMAL_CTX_new, version OPENSSL_3.0.3 not defined in file libcrypto.so.3 with link time reference
操作过程如下：
首先，下载包编译参数，目录为/usr/local/tongsuo-debug
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/49789525/fb416473-38cf-477c-a539-0903a7befd0f)

可以看到ec_elgamal状态是enable
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/49789525/0a971e00-cdf0-40de-b119-b3f198c71b5a)
make（之前装的环境无截图）
make install（之前装的环境无截图）
得到目录
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/49789525/7746cd8d-0675-4aef-bab1-5556fe5eeac7)
按照测试用例编译、运行
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/49789525/e184bfe5-a912-4fd1-9984-64658262148e)
注：测试用例的25、27行，直接编译会报错EC_ELGAMAL_CTX_new函数缺少参数，我猜测是因为代码更新，经过简单的代码检查，将
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/49789525/bacb8e22-94ca-473c-84c2-06998b302a7d)

补充为
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/49789525/117b693a-e68a-4118-ae7e-f8f6cf43a3e9)

由于刚开始使用本库，不确定这个补充方法是否正确。但是推测报错应该与该问题相关度可能较低。

**Comment by wa5i** [comment]
这是找到 tongsuo 的动态库导致的，gcc 加个参数：-Wl,-rpath,/usr/local/tongsuo-debug/lib64，重新编译试试，或者运行时加环境变量：LD_LIBRARY_PATH=/usr/local/tongsuo-debug/lib64 ./ec_elgamal_test

**Comment by lit18329436479** [comment]
谢谢，已解决~

**Comment by wa5i** [comment]
问题已解决，我把这个 issue 关闭了
