### ISSUE TITLE
SM2证书的AlgorithmIdentifier与标准定义不一致

### ISSUE THREAD

**Issue by lirc571** [Tongsuo-Project/Tongsuo#477]
GMT 0015-2012中表C.3定义AlgorithmIdentifier.algorithm为SM2算法的OID(1.2.156.10197.1.301)，OpenSSL也是这样实现的。铜锁里却设成了标准EC公钥的ecPublicKey(1.2.840.10045.2.1)，导致铜锁和OpenSSL生成的证书和CSR不兼容。是否应该符合标准？

**Comment by zzl360** [comment]
参考0015附录D.2以及0010附录A.2。openssl的实现并不一定就符合标准

**Comment by lirc571** [comment]
> 参考0015附录D.2以及0010附录A.2。openssl的实现并不一定就符合标准

谢谢回复。那这两种都可以吗？应该两种都支持？现在主流的支持国密的应用一般用的哪种实现呢 :frowning:

**Comment by zzl360** [comment]
目前国内CA包括rootca在内，签发的证书用的都是铜锁的实现方式（也是openssl1.x版本的实现方式，openssl3.0才把这块给改了）

**Comment by lirc571** [comment]
> 目前国内CA包括rootca在内，签发的证书用的都是铜锁的实现方式（也是openssl1.x版本的实现方式，openssl3.0才把这块给改了）

了解了，谢谢！
