### ISSUE TITLE
上周修改nginx源码添加国密tls，报SSL_do_handshake() failed (SSL: error:0A0000C1:SSL routines::no shared cipher) while SSL handshaking

### ISSUE THREAD

**Issue by tengliu0929** [Tongsuo-Project/Tongsuo#489]
上周用铜锁源码给新版nginx添加国密tls功能，给tongsuo-master加的编译选项是 enable-ntls,

我对nginx的编译脚本如下
`#!/bin/bash

NG_SRC=/home/nginx-1.25.2
OPENSSL_SRC=/home/Tongsuo-master

rm -rf ${NR_SRC}
cp -r /mnt/hgfs/code/nginx1.25.2/src/nginx-1.25.2 /home

cd ${NG_SRC}

./configure --with-debug --prefix=/opt/nginx --with-http_ssl_module --with-openssl=${OPENSSL_SRC} --with-openssl-opt=enable-ntls

make -j4
make install`
编译后tongsuo所支持的套件如下
`TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_SM4_GCM_SM3:TLS_SM4_CCM_SM3:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:RSA-PSK-AES256-GCM-SHA384:DHE-PSK-AES256-GCM-SHA384:RSA-PSK-CHACHA20-POLY1305:DHE-PSK-CHACHA20-POLY1305:ECDHE-PSK-CHACHA20-POLY1305:AES256-GCM-SHA384:PSK-AES256-GCM-SHA384:PSK-CHACHA20-POLY1305:RSA-PSK-AES128-GCM-SHA256:DHE-PSK-AES128-GCM-SHA256:AES128-GCM-SHA256:PSK-AES128-GCM-SHA256:ECC-SM2-SM4-GCM-SM3:ECDHE-SM2-SM4-GCM-SM3:RSA-SM4-GCM-SHA256:RSA-SM4-GCM-SM3:AES256-SHA256:AES128-SHA256:ECDHE-PSK-AES256-CBC-SHA384:ECDHE-PSK-AES256-CBC-SHA:SRP-RSA-AES-256-CBC-SHA:SRP-AES-256-CBC-SHA:RSA-PSK-AES256-CBC-SHA384:DHE-PSK-AES256-CBC-SHA384:RSA-PSK-AES256-CBC-SHA:DHE-PSK-AES256-CBC-SHA:AES256-SHA:PSK-AES256-CBC-SHA384:PSK-AES256-CBC-SHA:ECDHE-PSK-AES128-CBC-SHA256:ECDHE-PSK-AES128-CBC-SHA:SRP-RSA-AES-128-CBC-SHA:SRP-AES-128-CBC-SHA:RSA-PSK-AES128-CBC-SHA256:DHE-PSK-AES128-CBC-SHA256:RSA-PSK-AES128-CBC-SHA:DHE-PSK-AES128-CBC-SHA:ECC-SM2-SM4-CBC-SM3:ECDHE-SM2-SM4-CBC-SM3:AES128-SHA:RSA-SM4-CBC-SHA256:RSA-SM4-CBC-SM3:PSK-AES128-CBC-SHA256:PSK-AES128-CBC-SHA`

我选择套件ECC-SM2-WITH-SM4-SM3和ECDHE-SM2-WITH-SM4-SM3，在nginx配置文件里也设置了，手写代码，测试客户端和服务端是通的，但客户端测试nginx就会报标题的错误了
2023/09/18 10:19:39 [info] 77164#0: *1 SSL_do_handshake() failed (SSL: error:0A0000C1:SSL routines::no shared cipher) while SSL handshaking, client: 127.0.0.1, server: 0.0.0.0:443
不知道怎么回事，当然一些套件是没有的，我用有的套件测试，但没有成功

**Comment by tengliu0929** [comment]
Need help, anyone can help, appreciate .

**Comment by wa5i** [comment]
目前 nginx 还没支持国密协议，需要自己去移植 tengine或者angie 的 patch 过来才可以。
参考文档：
https://www.yuque.com/tsdoc/ts/eziua1
https://www.yuque.com/tsdoc/ts/xy1vvzogtycvh4ob

**Comment by tengliu0929** [comment]
> 目前 nginx 还没支持国密协议，需要自己去移植 tengine或者angie 的 patch 过来才可以。 参考文档： https://www.yuque.com/tsdoc/ts/eziua1 https://www.yuque.com/tsdoc/ts/xy1vvzogtycvh4ob

你好，我想你没看清楚我的问题，我的问题是，我手动改动nginx源码，通过Tongsuo版本的openssl向nginx源码添加国密功能，改动后，不清楚哪里错了。手写代码客户端和服务端通了后，才按照代码去修改nginx源码，然后用客户端去请求
plus:
    用angie同样的证书去测试，会报
 SSL_do_handshake() failed (SSL: error:0A0000B0:SSL routines::no certificates returned) while SSL handshaking
所以想手动修改代码，将tongsuo库融入到nginx源码中

**Comment by wa5i** [comment]
那可能是你移植的不全，你把 nginx 的配置和客户端命令贴上来看看

**Comment by tengliu0929** [comment]
> 那可能是你移植的不全，你把 nginx 的配置和客户端命令贴上来看看
patch是我自最新源码的，只增加了http模块下的国密ssl功能
nginx.txt是我的配植
nginx.tar.gz是我编译后的安装包
tongsuo.tar.gz 是我测试程序，包括服务端和客户端
希望能得到一些帮助，谢谢

[nginx.1.25.2.patch](https://github.com/Tongsuo-Project/Tongsuo/files/12646092/nginx.1.25.2.patch)
[nginx.txt](https://github.com/Tongsuo-Project/Tongsuo/files/12646105/nginx.txt)
[nginx.tar.gz](https://github.com/Tongsuo-Project/Tongsuo/files/12646117/nginx.tar.gz)
[tongsuo.tar.gz](https://github.com/Tongsuo-Project/Tongsuo/files/12646125/tongsuo.tar.gz)

**Comment by wa5i** [comment]
看了下你的 patch，ngx_http_gmssl_enable 函数并没有设置 gmssl_enable：
<img width="546" alt="image" src="https://github.com/Tongsuo-Project/Tongsuo/assets/7484739/2d350207-50e2-46f7-b403-a9cd08ac6b43">

**Comment by tengliu0929** [comment]
> 看了下你的 patch，ngx_http_gmssl_enable 函数并没有设置 gmssl_enable： <img alt="image" width="546" src="https://user-images.githubusercontent.com/7484739/268609999-2d350207-50e2-46f7-b403-a9cd08ac6b43.png"
好像我调这个就能把gmssl_enable设置了，不行我明天试下，gdb调下就知道会不会设置了

**Comment by tengliu0929** [comment]
> 看了下你的 patch，ngx_http_gmssl_enable 函数并没有设置 gmssl_enable： <img alt="image" width="546" src="https://user-images.githubusercontent.com/7484739/268609999-2d350207-50e2-46f7-b403-a9cd08ac6b43.png">

我昨天突然想起来，你说的地方不对，这里有ngx_conf_set_flag_slot，能够设置gmssl_enalbe为1,刚才我写日志测了下，gmssl_enable能设置成1的，以往nginx版本的ssl开关也是这么做的
nginx: [emerg] sscf->gmssl_enable [1]

**Comment by wa5i** [comment]
> > 看了下你的 patch，ngx_http_gmssl_enable 函数并没有设置 gmssl_enable： <img alt="image" width="546" src="https://user-images.githubusercontent.com/7484739/268609999-2d350207-50e2-46f7-b403-a9cd08ac6b43.png">
> 
> 我昨天突然想起来，你说的地方不对，这里有ngx_conf_set_flag_slot，能够设置gmssl_enalbe为1,刚才我写日志测了下，gmssl_enable能设置成1的，以往nginx版本的ssl开关也是这么做的 nginx: [emerg] sscf->gmssl_enable [1]

哦哦，我没注意你的ngx_http_gmssl_enable调用了ngx_conf_set_flag_slot。我再看一下 patch

**Comment by tengliu0929** [comment]
> > > 看了下你的 patch，ngx_http_gmssl_enable 函数并没有设置 gmssl_enable： <img alt="image" width="546" src="https://user-images.githubusercontent.com/7484739/268609999-2d350207-50e2-46f7-b403-a9cd08ac6b43.png">
> > 
> > 
> > 我昨天突然想起来，你说的地方不对，这里有ngx_conf_set_flag_slot，能够设置gmssl_enalbe为1,刚才我写日志测了下，gmssl_enable能设置成1的，以往nginx版本的ssl开关也是这么做的 nginx: [emerg] sscf->gmssl_enable [1]
> 
> 哦哦，我没注意你的ngx_http_gmssl_enable调用了ngx_conf_set_flag_slot。我再看一下 patch

其实我能定位到tls_post_process_client_hello_ntls -->  ssl3_choose_cipher --> retry后的匹配套件的for循环

**Comment by tengliu0929** [comment]
> > > 看了下你的 patch，ngx_http_gmssl_enable 函数并没有设置 gmssl_enable： <img alt="image" width="546" src="https://user-images.githubusercontent.com/7484739/268609999-2d350207-50e2-46f7-b403-a9cd08ac6b43.png">
> > 
> > 
> > 我昨天突然想起来，你说的地方不对，这里有ngx_conf_set_flag_slot，能够设置gmssl_enalbe为1,刚才我写日志测了下，gmssl_enable能设置成1的，以往nginx版本的ssl开关也是这么做的 nginx: [emerg] sscf->gmssl_enable [1]
> 
> 哦哦，我没注意你的ngx_http_gmssl_enable调用了ngx_conf_set_flag_slot。我再看一下 patch
请问看到哪不对了吗，我调试还是没有进度，也没找到问题所在，请指明一下，多谢了

**Comment by tengliu0929** [comment]
> > > 看了下你的 patch，ngx_http_gmssl_enable 函数并没有设置 gmssl_enable： <img alt="image" width="546" src="https://user-images.githubusercontent.com/7484739/268609999-2d350207-50e2-46f7-b403-a9cd08ac6b43.png">
> > 
> > 
> > 我昨天突然想起来，你说的地方不对，这里有ngx_conf_set_flag_slot，能够设置gmssl_enalbe为1,刚才我写日志测了下，gmssl_enable能设置成1的，以往nginx版本的ssl开关也是这么做的 nginx: [emerg] sscf->gmssl_enable [1]
> 
> 哦哦，我没注意你的ngx_http_gmssl_enable调用了ngx_conf_set_flag_slot。我再看一下 patch

我用北大的gmssl第二个版本来实现http ssl模块的国密功能，是可以通的，是不是铜锁版本哪块有问题哈，请教一下

**Comment by wa5i** [comment]
我自己编译和 gdb 了一下，找到原因了，是没有配置上国密证书的原因，解析和设置证书时走了红框的逻辑，而 ngx_http_ssl_certificate -> ngx_ssl_connection_certificate 里面没有调用国密接口设置国密证书：
<img width="699" alt="image" src="https://github.com/Tongsuo-Project/Tongsuo/assets/7484739/2e25cd3e-8711-4306-bfaa-10fc29ea50cc">

**Comment by tengliu0929** [comment]
我仔细看了看，确实是这里，ngx_http_ssl_certificate不应该调这个函数ngx_ssl_connection_certificate，我得重新定义两个函数来实现。十分感谢了，这块我确实没仔细看，光看另一块了，当局者迷啊。
