### ISSUE TITLE
tongsuo编译安装时报错："cp: './include/openssl/asn1.h' and '/home/db/zkps/Tongsuo/tongsuo-build//include/openssl/asn1.h' are the same file"

### ISSUE THREAD

**Issue by nihaoqingtuan** [Tongsuo-Project/Tongsuo#514]
log:
`
...
...
install ./include/openssl/asn1.h -> /home/db/zkps/Tongsuo/tongsuo-build//include/openssl/asn1.h
cp: './include/openssl/asn1.h' and '/home/db/zkps/Tongsuo/tongsuo-build//include/openssl/asn1.h' are the same file
make: *** [Makefile:2102：install_dev] 错误 1

`

**Comment by dongbeiouba** [comment]
先临时改一下Makefile，2102行，cp 改成 cp -f试试

**Comment by nihaoqingtuan** [comment]
改完之后：
$ sudo make install
make depend && make _build_libs                                                                                                                                       
make[1]: Entering directory '/home/db/zkps/Tongsuo/tongsuo-build'                                                                                     
make[1]: Leaving directory '/home/db/zkps/Tongsuo/tongsuo-build'                                                                                      
make[1]: Entering directory '/home/db/zkps/Tongsuo/tongsuo-build'                                                                                     
gcc  -I. -Iinclude -Iapps/include -I.. -I../include -I../apps/include  -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/home/db/zkps/Tongsuo/tongsuo-build/ssl\"" -DENGINESDIR="\"/home/db/zkps/Tongsuo/tongsuo-build/lib64/engines-3\"" -DMODULESDIR="\"/home/db/zkps/Tongsuo/tongsuo-build/lib64/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF apps/lib/libapps-lib-app_libctx.d.tmp -MT apps/lib/libapps-lib-app_libctx.o -c -o apps/lib/libapps-lib-app_libctx.o ../apps/lib/app_libctx.c                                                           
/bin/sh: gcc: command not found                                                                                                                                       
make[1]: *** [Makefile:2781: apps/lib/libapps-lib-app_libctx.o] Error 127                                                                                             
make[1]: Leaving directory '/home/db/zkps/Tongsuo/tongsuo-build'                                                                                      
make: *** [Makefile:1927：build_libs] 错误 2

**Comment by dongbeiouba** [comment]
系统有安装gcc吗？which gcc

**Comment by nihaoqingtuan** [comment]
我先重新试下，改完后需要重新make吗，还是直接make install

**Comment by InfoHunter** [comment]
make install里包含了make的过程，因此哪个都行

**Comment by nihaoqingtuan** [comment]
报错是：make: *** [Makefile:2090：install_dev] 错误 1
我改了2094行：cp -f $$i $(DESTDIR)$(INSTALLTOP)/include/openssl/$$fn; \
![2023-11-02_11-08](https://github.com/Tongsuo-Project/Tongsuo/assets/112857116/a0e85f98-22ba-46a8-87a5-ad33e5e6c569)

**Comment by dongbeiouba** [comment]
猜测可能是将--prefix设置成了构建目录，可以尝试修改一下--prefix即可。
