### ISSUE TITLE
R1CS的教程中的demo代码报错：未定义标识符"BP_TRANSCRIPT"

### ISSUE THREAD

**Issue by nihaoqingtuan** [Tongsuo-Project/Tongsuo#515]
报错：
![2023-11-02_14-47_1](https://github.com/Tongsuo-Project/Tongsuo/assets/112857116/fa916c7a-7ec2-4bc6-8263-de7f1ca140c5)

我没有在include/openssl/bulletproofs.h中找到[教程](https://juejin.cn/post/7254793459122602045#heading-8:~:text=%E9%9B%B6%E7%9F%A5%E8%AF%86%E6%96%B9%E6%A1%88%E3%80%82-,%E5%88%9B%E5%BB%BA/%E9%87%8A%E6%94%BE,-arduino)的相关代码
![2023-11-02_14-47](https://github.com/Tongsuo-Project/Tongsuo/assets/112857116/43f554d5-ef27-45e8-8482-03429c80ab26)

头文件中也找不到BP_TRANSCRIPT变量。

**Comment by nihaoqingtuan** [comment]
是因为我没有成功安装的缘故吗。

**Comment by wa5i** [comment]
这是因为 BP_TRANSCRIPT 改成 ZKP_TRANSCRIPT 了，在铜锁的语雀文档中已更新：https://www.yuque.com/tsdoc/ts/bulletproofs-r1cs
