### ISSUE TITLE
bulletproofs的范围证明只能实现固定的0~2^n次方吗

### ISSUE THREAD

**Issue by nihaoqingtuan** [Tongsuo-Project/Tongsuo#516]

**Comment by InfoHunter** [comment]
Ping @wa5i

**Comment by InfoHunter** [comment]
我理解标准的Bulletproofs是这样，但是基于Twisted ElGamal的Bulletproofs可以实现范围2^k ~ 2^n的证明

**Comment by wa5i** [comment]
标准 bulletproofs 可能证明和验证的范围是 [0, 2^n)，而且，n 必须是2的幂次方。基于Twisted ElGamal的优化后，可以实现的范围是 [2^m, 2^k)，其中 m<k<=n，pr 是这个：https://github.com/Tongsuo-Project/Tongsuo/pull/454

**Comment by nihaoqingtuan** [comment]
感谢。
