### ISSUE TITLE
SM4硬件加速的验证方法

### ISSUE THREAD

**Issue by zicaty** [Tongsuo-Project/Tongsuo#560]
按照文档（https://www.yuque.com/tsdoc/ts/eksg4u092ixd349k），使用
./Configure -march=native
make
编译后，SM4性能可提高到未优化时的2.5倍左右。

请问，具应该如何验证这个优化？
尝试过：
1、使用openssl speed sm4 : 使用-march=native编译后，性能降低了（16K从89396.57k降低到26962.60k）
2、使用examples/perf/tsm/perf：使用-march=native编译后，性能反而降低了（sm4-ecb-enc从741降低到206，其它sm2的性能也都在降低）。

CPU：海光5380

**Comment by zzl360** [comment]
操作系统是什么呢？

**Comment by zicaty** [comment]
操作系统是UOS V20 SP1，大约是2019年的版本，对应Debian 10。

**Comment by zzl360** [comment]
测试的字节数是什么？麻烦把测试的对比数据发一下。
如果使用的是16字节数据测试的话，是会导致性能下降的

**Comment by zicaty** [comment]
没有指定测试字节数：

- openssl speed的命令和结果是：

root@PC:~/tongsuo/Tongsuo-8.4.0/examples/perf/tsm# /usr/local/bin/tongsuo speed sm4
Doing sm4 for 3s on 16 size blocks: 4802674 sm4's in 3.00s
Doing sm4 for 3s on 64 size blocks: 1254660 sm4's in 3.00s
Doing sm4 for 3s on 256 size blocks: 315195 sm4's in 3.00s
Doing sm4 for 3s on 1024 size blocks: 77838 sm4's in 3.00s
Doing sm4 for 3s on 8192 size blocks: 9859 sm4's in 3.00s
Doing sm4 for 3s on 16384 size blocks: 4937 sm4's in 3.00s
version: 3.0.3
built on: Tue Dec 26 10:42:35 2023 UTC
options: bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG 
CPUINFO: OPENSSL_ia32cap=0x7ed8320b078bffff:0x209c01a9
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
sm4              25614.26k    26766.08k    26896.64k    26568.70k    26921.64k    26962.60k

- examples/perf/tsm/perf的命令和结果是：

root@PC:~/tongsuo/Tongsuo-8.4.0/examples/perf/tsm# ./perf
Iteration 0: sm2-enc: 244, sm2-dec: 250, sm2-sign: 1680, sm2-verify: 1824, sm2-keygen: 1029, sm3-hash: 1559, sm4-ecb-enc: 719, sm4-cbc-enc: 683, sm4-ecb-dec: 718, sm4-cbc-dec: 730
Iteration 1: sm2-enc: 250, sm2-dec: 255, sm2-sign: 1692, sm2-verify: 1845, sm2-keygen: 1569, sm3-hash: 1559, sm4-ecb-enc: 742, sm4-cbc-enc: 683, sm4-ecb-dec: 717, sm4-cbc-dec: 729
...

**Comment by dongbeiouba** [comment]
> 按照文档（[https://www.yuque.com/tsdoc/ts/eksg4u092ixd349k），使用](https://www.yuque.com/tsdoc/ts/eksg4u092ixd349k%EF%BC%89%EF%BC%8C%E4%BD%BF%E7%94%A8) ./Configure -march=native make 编译后，SM4性能可提高到未优化时的2.5倍左右。
> 
> 请问，具应该如何验证这个优化？ 尝试过： 1、使用openssl speed sm4 : 使用-march=native编译后，性能降低了（16K从89396.57k降低到26962.60k） 2、使用examples/perf/tsm/perf：使用-march=native编译后，性能反而降低了（sm4-ecb-enc从741降低到206，其它sm2的性能也都在降低）。
> 
> CPU：海光5380

https://www.yuque.com/tsdoc/ts/eksg4u092ixd349k里面给的数据是测试的SM4-GCM，可以使用如下命令测试：

```
/opt/tongsuo/bin/openssl speed -evp sm4-gcm
```

**Comment by zicaty** [comment]
说明：/usr/local/lib64是./Configure -march=native make的库，/usr/local/tongsuo/lib64是./config -prefix=/usr/local/tongsuo; make编译的
性能测试结果显示，“./Configure -march=native make”的性能低了很多。

root@koal-PC:/usr/local/bin# echo $LD_LIBRARY_PATH 
/usr/local/lib64/
root@koal-PC:/usr/local/bin# ./tongsuo speed -evp sm4-gcm
Doing SM4-GCM for 3s on 16 size blocks: 4611839 SM4-GCM's in 3.00s
Doing SM4-GCM for 3s on 64 size blocks: 1232338 SM4-GCM's in 3.00s
Doing SM4-GCM for 3s on 256 size blocks: 316426 SM4-GCM's in 3.00s
Doing SM4-GCM for 3s on 1024 size blocks: 78346 SM4-GCM's in 3.00s
Doing SM4-GCM for 3s on 8192 size blocks: 9593 SM4-GCM's in 3.00s
Doing SM4-GCM for 3s on 16384 size blocks: 4871 SM4-GCM's in 3.00s
version: 3.0.3
built on: Tue Dec 26 10:42:35 2023 UTC
options: bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG 
CPUINFO: OPENSSL_ia32cap=0x7ed8320b078bffff:0x209c01a9
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
SM4-GCM          24596.47k    26289.88k    27001.69k    26742.10k    26195.29k    26602.15k
root@koal-PC:/usr/local/bin# export LD_LIBRARY_PATH=/usr/local/tongsuo/lib64/
root@koal-PC:/usr/local/bin# ./tongsuo speed -evp sm4-gcm
Doing SM4-GCM for 3s on 16 size blocks: 13276408 SM4-GCM's in 3.00s
Doing SM4-GCM for 3s on 64 size blocks: 4101489 SM4-GCM's in 3.00s
Doing SM4-GCM for 3s on 256 size blocks: 1092086 SM4-GCM's in 3.00s
Doing SM4-GCM for 3s on 1024 size blocks: 277748 SM4-GCM's in 3.00s
Doing SM4-GCM for 3s on 8192 size blocks: 34842 SM4-GCM's in 3.00s
Doing SM4-GCM for 3s on 16384 size blocks: 17426 SM4-GCM's in 2.99s
version: 3.0.3
built on: Tue Dec 26 10:42:35 2023 UTC
options: bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG 
CPUINFO: OPENSSL_ia32cap=0x7ed8320b078bffff:0x209c01a9
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
SM4-GCM          70807.51k    87498.43k    93191.34k    94804.65k    95141.89k    95487.49k

**Comment by zzl360** [comment]
@zicaty 可以试试intel/amd的情况，来排除cpu的影响
