### ISSUE TITLE
tongsuo签名结果与openssl签名结果不互通

### ISSUE THREAD

**Issue by j1nj1CL** [Tongsuo-Project/Tongsuo#570]
在使用tongsuo 对数据进行sm2签名时，发现其签名结果不能被openssl验证，分析得知在结果进行asn1编码时二者存在差异
openssl
![1705543624284](https://github.com/Tongsuo-Project/Tongsuo/assets/153585120/3a09e98a-24d3-4011-8d80-14b8199bb15e)
tongsuo
![图片](https://github.com/Tongsuo-Project/Tongsuo/assets/153585120/b1fba6f0-49e8-48fd-9364-c5be285d4771)
openssl在最高位为1时增加了00的标志位，查阅itu x690中对于asn1编码规则的介绍，integer是以补码形式存储的
![图片](https://github.com/Tongsuo-Project/Tongsuo/assets/153585120/1c83ea10-869e-4e4f-a87a-16662e152387)
虽说针对签名结果rs都为正数，可以不用特意区分，但普适来讲补码表示正数是不是应该加上00与负数进行区分，也能更好地与openssl互通
ps：gmssl签名也是没加00标志，这是国内特有表示方式么  （-。-）

**Comment by zzl360** [comment]
参考http://www.gmbz.org.cn/main/viewfile/2018011001400692565.html ，《GM/T 0009 SM2 密码算法使用规范》7.3章节
![image](https://github.com/Tongsuo-Project/Tongsuo/assets/100331525/a44a2158-8056-4950-ab35-ef24db97ddf6)

**Comment by j1nj1CL** [comment]
tongsuo好像在某次更新中更改了签名结果的格式
目前tongsuo的签名中添加了00标志，此时不符合0009的规范
![图片](https://github.com/Tongsuo-Project/Tongsuo/assets/153585120/b83e1061-f1d3-4279-9eb5-2c62ec0eab4d)
![图片](https://github.com/Tongsuo-Project/Tongsuo/assets/153585120/29cab033-5ae8-471f-aea9-56b7eaa229a7)

**Comment by InfoHunter** [comment]
什么版本的tongsuo加了00？master分支？

**Comment by j1nj1CL** [comment]
MASTER分支

**Comment by j1nj1CL** [comment]
不互通原因为openssl的sm2_id默认为空，即不计算z值，并非00原因
