### ISSUE TITLE
在openEuler-22.03-LTS-loongarch64下编译和安装铜锁成功，可是执行tongsuo命令失败

### ISSUE THREAD

**Issue by yiyi99** [Tongsuo-Project/Tongsuo#600]
按文档编译源码成功。
[root@localhost ~]# ls -l /opt/tongsuo
总用量 16
drwxr-xr-x 2 root root 4096  4月 24 20:26 bin
drwxr-xr-x 3 root root 4096  4月 24 20:26 include
drwxr-xr-x 5 root root 4096  4月 24 20:40 lib
drwxr-xr-x 5 root root 4096  4月 24 20:26 ssl
[root@localhost ~]# ls -l /opt/tongsuo/lib
总用量 70236
drwxr-xr-x 2 root root     4096  4月 24 20:26 engines-3
-rw-r--r-- 1 root root 45021082  4月 24 20:26 libcrypto.a
lrwxrwxrwx 1 root root       14  4月 24 20:26 libcrypto.so -> libcrypto.so.3
-rwxr-xr-x 1 root root 11097016  4月 24 20:26 libcrypto.so.3
-rw-r--r-- 1 root root 12826642  4月 24 20:26 libssl.a
lrwxrwxrwx 1 root root       11  4月 24 20:26 libssl.so -> libssl.so.3
-rwxr-xr-x 1 root root  2968536  4月 24 20:26 libssl.so.3
drwxr-xr-x 2 root root     4096  4月 24 20:26 ossl-modules
drwxr-xr-x 2 root root     4096  4月 24 20:26 pkgconfig
[root@localhost ~]# /opt/tongsuo/bin/tongsuo version
/opt/tongsuo/bin/tongsuo: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
使用：
ln -s /opt/tongsuo/lib/libssl.so.3 /usr/lib/libssl.so.3
ln -s /opt/tongsuo/lib/libcrypto.so.3 /usr/lib/libcrypto.so.3
后执行同样的错误，操作系统版本如下：
[root@localhost ~]# uname -a
Linux localhost.localdomain 5.10.0-60.116.0.143.oe2203.loongarch64 #1 SMP Fri Nov 10 16:39:05 UTC 2023 loongarch64 loongarch64 loongarch64 GNU/Linux

**Comment by yiyi99** [comment]
正常了，原因应该是tongsuo调用库的路径应该是/opt/tongsuo/lib64，只需要：
make /opt/tongsuo/lib64
cp -r /opt/tongsuo/lib /opt/tongsuo/lib64
就可以正常运行了。
[root@localhost bin]# ./tongsuo version
Tongsuo: Tongsuo 8.5.0-dev (Library: Tongsuo 8.5.0-dev)
OpenSSL 3.0.3 3 May 2022 (Library: OpenSSL 3.0.3 3 May 2022)

**Comment by yiyi99** [comment]
正常了，原因应该是tongsuo调用库的路径应该是/opt/tongsuo/lib64，只需要：
make /opt/tongsuo/lib64
cp -r /opt/tongsuo/lib /opt/tongsuo/lib64
就可以正常运行了。
[root@localhost bin]# ./tongsuo version
Tongsuo: Tongsuo 8.5.0-dev (Library: Tongsuo 8.5.0-dev)
OpenSSL 3.0.3 3 May 2022 (Library: OpenSSL 3.0.3 3 May 2022)

**Comment by fengzhao** [comment]
@yiyi99 

并不是，在Ubuntu 20.04.4 LTS上编译的，tongsuo调用的库路径依然是 /lib/x86_64-linux-gnu/

root@qhdata-dev:/opt/tongsuo/bin# ./tongsuo version
./tongsuo: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
root@qhdata-dev:/opt/tongsuo/bin# ldd tongsuo
        linux-vdso.so.1 (0x00007ffc080d9000)
        libssl.so.3 => not found
        libcrypto.so.3 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc5870c8000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc586ed6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc5871f3000)
root@qhdata-dev:/opt/tongsuo/bin#
root@qhdata-dev:/opt/tongsuo/bin# cp ../lib64/libcrypto.so.3  /lib/x86_64-linux-gnu/
root@qhdata-dev:/opt/tongsuo/bin# cp ../lib64/libssl.so.3  /lib/x86_64-linux-gnu/
root@qhdata-dev:/opt/tongsuo/bin# ldd tongsuo
        linux-vdso.so.1 (0x00007ffd7eb49000)
        libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007f0e0514d000)
        libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007f0e04cf0000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0e04ccd000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0e04adb000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0e04ad5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0e0531f000)
root@qhdata-dev:/opt/tongsuo/bin#

**Comment by zzl360** [comment]
> [@yiyi99](https://github.com/yiyi99)
> 
> 并不是，在Ubuntu 20.04.4 LTS上编译的，tongsuo调用的库路径依然是 /lib/x86_64-linux-gnu/
> 
> root@qhdata-dev:/opt/tongsuo/bin# ./tongsuo version ./tongsuo: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory root@qhdata-dev:/opt/tongsuo/bin# ldd tongsuo linux-vdso.so.1 (0x00007ffc080d9000) libssl.so.3 => not found libcrypto.so.3 => not found libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc5870c8000) libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc586ed6000) /lib64/ld-linux-x86-64.so.2 (0x00007fc5871f3000) root@qhdata-dev:/opt/tongsuo/bin# root@qhdata-dev:/opt/tongsuo/bin# cp ../lib64/libcrypto.so.3 /lib/x86_64-linux-gnu/ root@qhdata-dev:/opt/tongsuo/bin# cp ../lib64/libssl.so.3 /lib/x86_64-linux-gnu/ root@qhdata-dev:/opt/tongsuo/bin# ldd tongsuo linux-vdso.so.1 (0x00007ffd7eb49000) libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007f0e0514d000) libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007f0e04cf0000) libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0e04ccd000) libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0e04adb000) libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0e04ad5000) /lib64/ld-linux-x86-64.so.2 (0x00007f0e0531f000) root@qhdata-dev:/opt/tongsuo/bin#

编译的时候要加--rpath参数
git clone https://github.com/Tongsuo-Project/Tongsuo

cd Tongsuo

./config --prefix=/opt/tongsuo enable-ntls enable-ssl-trace -Wl,-rpath,/opt/tongsuo/lib64 --debug
make -j
make install
