### ISSUE TITLE
arm架构开启neon指令集加速aes算法似乎不生效

### ISSUE THREAD

**Issue by linju123455** [Tongsuo-Project/Tongsuo#654]
使用openssl speed测试aes-128-ctr：
![image](https://github.com/user-attachments/assets/d8fd9460-e6be-4027-a800-54fdeb47f77b)
这是开启-march=armv8-a+simd的效果
![image](https://github.com/user-attachments/assets/ad051449-3aa9-4645-90af-f17ee3f85f41)
这是不开启-march=armv8-a+simd的效果
可从compiler中看出确实是减少了-march=armv8-a+simd的选项，但是速率还是差不多的
![image](https://github.com/user-attachments/assets/fe847e5e-06bf-4ade-ac70-8b85b82db716)
由此可以见得，cpu是支持aes算法加速的
这是我开启硬件加速选项时的编译命令：./config --prefix=/home/linju/linju_workspace/third_party/Tongsuo-8.3.3-711C/install  enable-ntls no-shared no-asm enable-sm4 -march=armv8-a+simd CC=/home/linju/host/bin/aarch64-buildroot-linux-gnu-gcc CXX=/home/linju/host/bin/aarch64-buildroot-linux-gnu-g++，Tongsuo版本是8.3.3

**Comment by zzl360** [comment]
去掉no-asm  这个编译参数再看看

**Comment by linju123455** [comment]
> 去掉no-asm 这个编译参数再看看

去掉这个选项就会收到类似于下图的报错，说是引用了x86_64架构的汇编代码
![image](https://github.com/user-attachments/assets/2858fdd3-5f34-461f-9531-92c63651b2b7)


我是在x86架构下交叉编译armV8的程序，很奇怪为什么会把当前识别为x86架构

**Comment by zzl360** [comment]
configure的时候加上./Configure linux-aarch64

**Comment by linju123455** [comment]
> configure的时候加上./Configure linux-aarch64

感谢老哥指导，已解决
