### ISSUE TITLE
SM2优化签名性能测试【测试不到官方公开的签名2.3w测试数据】

### ISSUE THREAD

**Issue by ZeroAntelope** [Tongsuo-Project/Tongsuo#681]
铜锁最新master代码
编译配置/config enable-ec_sm2p_64_gcc_128
测试命令：./bin/tongsuo speed sm2
【测试环境1】
ubuntu20.04，Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz，Hypervisor vendor: Windows Subsystem for Linux，
total        used        free      shared  buff/cache   available
Mem:           15Gi        10Gi       5.2Gi        17Mi       223Mi       5.3Gi
Swap:          22Gi       196Mi        22Gi
【性能测试数据1基本信息】
Doing 256 bits sign CurveSM2's for 10s: 114635 256 bits CurveSM2 signs in 9.96s
Doing 256 bits verify CurveSM2's for 10s: 56217 256 bits CurveSM2 verify in 9.99s
version: 3.0.3
built on: Mon Dec 16 05:50:44 2024 UTC
options: bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0xfedaf387ffebffff:0x9c67af
                              sign    verify    sign/s verify/s
 256 bits SM2 (CurveSM2)   0.0001s   0.0002s  11509.5   5627.3

【测试环境2基本信息】
ubuntu20.04，Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz，
total        used        free      shared  buff/cache   available
Mem:          1.0Ti        80Gi       795Gi       3.0Mi       128Gi       917Gi
Swap:         8.0Gi       865Mi       7.2Gi
【性能测试数据2】
Doing 256 bits sign CurveSM2's for 10s: 95080 256 bits CurveSM2 signs in 10.00s
Doing 256 bits verify CurveSM2's for 10s: 48333 256 bits CurveSM2 verify in 10.00s
version: 3.0.3
built on: Tue Dec 17 06:23:37 2024 UTC
options: bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DO
CPUINFO: OPENSSL_ia32cap=0x7ffef3ffffebffff:0x40417f5ef3bfb7ef
                              sign    verify    sign/s verify/s
 256 bits SM2 (CurveSM2)   0.0001s   0.0002s   9508.0   4833.3

【测试环境3基本信息】
ubuntu20.04，AMD EPYC 7542 32-Core Processor，Hypervisor vendor: VMware，
total        used        free      shared  buff/cache   available
Mem:          7.8Gi       404Mi       3.1Gi       1.0Mi       4.3Gi       7.1Gi
Swap:         4.0Gi          0B       4.0Gi
【性能测试数据3】
Doing 256 bits sign CurveSM2's for 10s: 99819 256 bits CurveSM2 signs in 9.99s
Doing 256 bits verify CurveSM2's for 10s: 49035 256 bits CurveSM2 verify in 10.00s
version: 3.0.3
built on: Mon Dec 16 08:45:12 2024 UTC
options: bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DO
CPUINFO: OPENSSL_ia32cap=0xfef83203078bffff:0x400004219c01a9
                              sign    verify    sign/s verify/s
 256 bits SM2 (CurveSM2)   0.0001s   0.0002s   9991.9   4903.5

**Comment by zhsnew** [comment]
不同的CPU性能差别比较大

测试1，签名 16, 839：
11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz   CPU @ 4.2GHz
version: 3.0.3
options: bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0x7ffaf3bfffebffff:0x405f5ef2bf67eb
                              sign    verify    sign/s verify/s
 256 bits SM2 (CurveSM2)   0.0001s   0.0001s  16839.8   8247.6

测试2， 签名 26, 840：
version: 3.0.3
options: bn(64,64)
compiler: GCC-14 -fPIC -arch arm64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: OPENSSL_armcap=0x7f
                              sign    verify    sign/s verify/s
 256 bits SM2 (CurveSM2)   0.0000s   0.0001s  26840.2  13023.8
